const darkMap = '''
[
  {"elementType": "geometry", "stylers": [{"color": "#242f3e"}, {"visibility": "on"}]},
  {"elementType": "labels.text.fill", "stylers": [{"color": "#746855"}, {"visibility": "on"}]},
  {"elementType": "labels.text.stroke", "stylers": [{"color": "#242f3e"}, {"visibility": "on"}]},
  {"featureType": "administrative", "elementType": "labels.text.fill", "stylers": [{"color": "#d59563"}, {"visibility": "on"}]},
  {"featureType": "administrative.country", "elementType": "labels.text.fill", "stylers": [{"color": "#aba0a0"}, {"visibility": "off"}]},
  {"featureType": "administrative.land_parcel", "elementType": "labels.text.fill", "stylers": [{"color": "#aba0a0"}, {"visibility": "on"}]},
  {"featureType": "administrative.locality", "elementType": "labels.text.fill", "stylers": [{"color": "#d59563"}, {"visibility": "on"}]},
  {"featureType": "administrative.neighborhood", "elementType": "labels.text.fill", "stylers": [{"color": "#aba0a0"}, {"visibility": "on"}]},
  {"featureType": "administrative.province", "elementType": "labels.text.fill", "stylers": [{"color": "#aba0a0"}, {"visibility": "on"}]},
  {"featureType": "landscape", "elementType": "labels.text.fill", "stylers": [{"color": "#9ca5b3"}, {"visibility": "on"}]},
  {"featureType": "landscape.man_made", "elementType": "geometry", "stylers": [{"color": "#2d2d3c"}, {"visibility": "on"}]},
  {"featureType": "landscape.natural", "elementType": "geometry", "stylers": [{"color": "#2d323c"}]},
  {"featureType": "poi", "elementType": "labels.icon", "stylers": [{"visibility": "off"}]},
  {"featureType": "poi", "elementType": "labels.text.fill", "stylers": [{"color": "#d59563"}, {"visibility": "on"}]},
  {"featureType": "poi.park", "elementType": "geometry", "stylers": [{"color": "#203220"}, {"visibility": "on"}]},
  {"featureType": "poi.park", "elementType": "labels.text.fill", "stylers": [{"color": "#648c64"}]},
  {"featureType": "road", "elementType": "geometry", "stylers": [{"color": "#38414e"}]},
  {"featureType": "road", "elementType": "geometry.stroke", "stylers": [{"color": "#212a37"}]},
  {"featureType": "road", "elementType": "labels.text.fill", "stylers": [{"color": "#9ca5b3"}, {"visibility": "on"}]},
  {"featureType": "road.arterial", "elementType": "geometry.fill", "stylers": [{"color": "#787878"}]},
  {"featureType": "road.highway", "elementType": "geometry", "stylers": [{"color": "#746855"}]},
  {"featureType": "road.highway", "elementType": "geometry.fill", "stylers": [{"color": "#9ca5b3"}]},
  {"featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{"color": "#1f2835"}]},
  {"featureType": "road.highway", "elementType": "labels.text.fill", "stylers": [{"color": "#f3d19c"}]},
  {"featureType": "road.local", "elementType": "geometry.fill", "stylers": [{"color": "#646464"}]},
  {"featureType": "transit", "elementType": "geometry", "stylers": [{"color": "#2f3948"}]},
  {"featureType": "transit", "elementType": "labels.text.fill", "stylers": [{"color": "#9ca5b3"}, {"visibility": "on"}]},
  {"featureType": "transit.station", "elementType": "labels.text.fill", "stylers": [{"color": "#d59563"}]},
  {"featureType": "water", "elementType": "geometry", "stylers": [{"color": "#17263c"}]},
  {"featureType": "water", "elementType": "labels.text.fill", "stylers": [{"color": "#515c6d"}, {"visibility": "on"}]},
  {"featureType": "water", "elementType": "labels.text.stroke", "stylers": [{"color": "#17263c"}]}
]
''';

const lightMap = '''
[
  {"elementType": "geometry", "stylers": [{"color": "#ebe3cd"}, {"visibility": "on"}]},
  {"elementType": "labels.text.fill", "stylers": [{"color": "#523735"}, {"visibility": "on"}]},
  {"elementType": "labels.text.stroke", "stylers": [{"color": "#f5f1e6"}, {"visibility": "on"}]},
  {"featureType": "administrative", "elementType": "geometry.stroke", "stylers": [{"color": "#c9b2a6"}]},
  {"featureType": "administrative", "elementType": "labels.text.fill", "stylers": [{"color": "#523735"}, {"visibility": "on"}]},
  {"featureType": "administrative.country", "elementType": "labels.text.fill", "stylers": [{"color": "#523735"}, {"visibility": "on"}]},
  {"featureType": "administrative.land_parcel", "elementType": "geometry.stroke", "stylers": [{"color": "#dcd2be"}]},
  {"featureType": "administrative.land_parcel", "elementType": "labels.text.fill", "stylers": [{"color": "#523735"}, {"visibility": "on"}]},
  {"featureType": "administrative.locality", "elementType": "labels.text.fill", "stylers": [{"color": "#523735"}, {"visibility": "on"}]},
  {"featureType": "administrative.neighborhood", "elementType": "labels.text.fill", "stylers": [{"color": "#523735"}, {"visibility": "on"}]},
  {"featureType": "administrative.province", "elementType": "labels.text.fill", "stylers": [{"color": "#523735"}, {"visibility": "on"}]},
  {"featureType": "landscape", "elementType": "geometry", "stylers": [{"color": "#c9b2a6"}, {"visibility": "on"}]},
  {"featureType": "landscape.natural", "elementType": "geometry", "stylers": [{"color": "#aabeaa"}]},
  {"featureType": "poi", "elementType": "geometry", "stylers": [{"color": "#dfd2ae"}]},
  {"featureType": "poi", "elementType": "labels.icon", "stylers": [{"visibility": "off"}]},
  {"featureType": "poi", "elementType": "labels.text.fill", "stylers": [{"color": "#93817c"}, {"visibility": "on"}]},
  {"featureType": "poi.park", "elementType": "geometry.fill", "stylers": [{"color": "#6e967d"}, {"visibility": "on"}]},
  {"featureType": "poi.park", "elementType": "labels.text.fill", "stylers": [{"color": "#447530"}, {"visibility": "on"}]},
  {"featureType": "road", "elementType": "geometry", "stylers": [{"color": "#f5f1e6"}, {"visibility": "on"}]},
  {"featureType": "road", "elementType": "labels.text.fill", "stylers": [{"color": "#99a1c8"}, {"visibility": "on"}]},
  {"featureType": "road.arterial", "elementType": "geometry", "stylers": [{"color": "#fdfcf8"}]},
  {"featureType": "road.highway", "elementType": "geometry", "stylers": [{"color": "#f8c967"}]},
  {"featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{"color": "#e9bc62"}]},
  {"featureType": "road.highway.controlled_access", "elementType": "geometry", "stylers": [{"color": "#e98d58"}]},
  {"featureType": "road.highway.controlled_access", "elementType": "geometry.stroke", "stylers": [{"color": "#db8555"}]},
  {"featureType": "road.local", "elementType": "labels.text.fill", "stylers": [{"color": "#806b63"}]},
  {"featureType": "transit", "elementType": "labels.text.fill", "stylers": [{"color": "#99a1c8"}, {"visibility": "on"}]},
  {"featureType": "transit.line", "elementType": "geometry", "stylers": [{"color": "#dfd2ae"}]},
  {"featureType": "transit.line", "elementType": "labels.text.fill", "stylers": [{"color": "#8f7d77"}]},
  {"featureType": "transit.line", "elementType": "labels.text.stroke", "stylers": [{"color": "#ebe3cd"}]},
  {"featureType": "transit.station", "elementType": "geometry", "stylers": [{"color": "#dfd2ae"}]},
  {"featureType": "water", "elementType": "geometry.fill", "stylers": [{"color": "#99a1c8"}, {"visibility": "on"}]},
  {"featureType": "water", "elementType": "labels.text.fill", "stylers": [{"color": "#92998d"}, {"visibility": "on"}]}
]
''';
